[customizations.installer.kickstart]
contents = """
graphical
timezone Asia/Seoul

ignoredisk --only-use={DEFAULT_DISK}
clearpart --all --initlabel --drives={DEFAULT_DISK}
autopart --type=plain

user --name={DEFAULT_USER_NAME} --uid=1000 --groups=wheel --password {DEFAULT_USER_PASSWD} --plaintext

%post
echo "$(hostnamectl -j | jq -r .Chassis)-$(hostnamectl -j | jq -r .MachineID | cut -c 1-9)" | tee /etc/hostname > /dev/null
%end

reboot
"""
