name: "Workflow for Development & Debugging"
run-name: "Dev & Debug Workflow - ${{ github.ref }}"

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: template
        run: |
          echo "this is template"
