name: "Merge Queue"

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: write

jobs:
  lint-dockerfile:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        id: lint-dockerfile
        uses: ./.github/actions/lint-dockerfile
        with:
          dockerfile-path: ./Dockerfile
          config-path: ./tools/hadolint.yaml
    
      - name: Add Dockerfile Lint Result to PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const title = "### Dockerfile Lint Result";
            const artifact = fs.readFileSync('${{ steps.lint-dockerfile.outputs.artifact }}', 'utf8');
            const commentBody = `${title}\ncommit hash : ${{ github.event.pull_request.head.sha || github.sha }}\n\`\`\`json\n${artifact}\n\`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  build-oci:
    needs: lint-dockerfile
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/_build-oci-container.yaml
    secrets: inherit
    with:
      runner-label: 'ytminipc001'
      oci_registry: 'quay.io'
      oci_image_repo: 'teamthepioneers/immutable-os-bootc'
      oci_image_tag: 'merge-queue-${{ github.event_name }}'
